[package]
name = "form_urlencoded"
version = "1.2.1"
authors = ["The rust-url developers"]
description = "Parser and serializer for the application/x-www-form-urlencoded syntax, as used by HTML forms."
categories = ["no_std"]
repository = "https://github.com/servo/rust-url"
license = "MIT OR Apache-2.0"
edition = "2018"
rust-version = "1.51"

[lib]
test = false

[features]
default = ["std"]
std = ["alloc", "percent-encoding/std"]
alloc = ["percent-encoding/alloc"]

[dependencies]
percent-encoding = { version = "2.3.0", default-features = false, path = "../percent_encoding" }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
